"""Tests for updater.py's current SHA256 release-asset verification."""

import hashlib

import pytest

import updater


class _FakeResponse:
    def __init__(self, text="", status_code=200):
        self.text = text
        self.status_code = status_code

    def raise_for_status(self):
        if self.status_code >= 400:
            raise RuntimeError(f"HTTP {self.status_code}")


@pytest.fixture
def tmp_file(tmp_path):
    path = tmp_path / "WinZapp.zip"
    path.write_bytes(b"pretend this is a WinZapp.zip release asset")
    return str(path)


def _sha256_of(path):
    h = hashlib.sha256()
    with open(path, "rb") as stream:
        h.update(stream.read())
    return h.hexdigest()


def test_find_sha256sums_asset_is_case_insensitive():
    assets = [
        {"name": "WinZapp.zip", "browser_download_url": "https://x/WinZapp.zip"},
        {"name": "sha256sums.TXT", "browser_download_url": "https://x/SHA256SUMS.txt"},
    ]
    assert updater._find_sha256sums_asset(assets) == "https://x/SHA256SUMS.txt"


def test_find_sha256sums_asset_returns_empty_when_absent():
    assert updater._find_sha256sums_asset([]) == ""
    assert updater._find_sha256sums_asset(
        [{"name": "WinZapp.zip", "browser_download_url": "https://x/WinZapp.zip"}]
    ) == ""


def test_no_manifest_url_fails_open_for_legacy_releases(tmp_file):
    ok, detail = updater._verify_sha256sums(tmp_file, "WinZapp.zip", "")
    assert ok is True
    assert detail == ""


def test_matching_checksum_passes(tmp_file, monkeypatch):
    expected = _sha256_of(tmp_file)
    manifest = f"{expected}  WinZapp.zip\n"
    monkeypatch.setattr(
        updater.requests, "get", lambda *a, **kw: _FakeResponse(manifest)
    )

    assert updater._verify_sha256sums(
        tmp_file, "WinZapp.zip", "https://x/SHA256SUMS.txt"
    ) == (True, "")


def test_mismatched_checksum_fails_closed(tmp_file, monkeypatch):
    manifest = f"{'0' * 64}  WinZapp.zip\n"
    monkeypatch.setattr(
        updater.requests, "get", lambda *a, **kw: _FakeResponse(manifest)
    )

    ok, detail = updater._verify_sha256sums(
        tmp_file, "WinZapp.zip", "https://x/SHA256SUMS.txt"
    )

    assert ok is False
    assert "mismatch" in detail.lower()


def test_missing_entry_fails_closed(tmp_file, monkeypatch):
    monkeypatch.setattr(
        updater.requests,
        "get",
        lambda *a, **kw: _FakeResponse("abc123  SomeOtherFile.zip\n"),
    )

    ok, detail = updater._verify_sha256sums(
        tmp_file, "WinZapp.zip", "https://x/SHA256SUMS.txt"
    )

    assert ok is False
    assert "no checksum entry" in detail.lower()


def test_manifest_fetch_failure_fails_closed(tmp_file, monkeypatch):
    def fail(*a, **kw):
        raise RuntimeError("network error")

    monkeypatch.setattr(updater.requests, "get", fail)

    ok, detail = updater._verify_sha256sums(
        tmp_file, "WinZapp.zip", "https://x/SHA256SUMS.txt"
    )

    assert ok is False
    assert "failed to download" in detail.lower()


def test_binary_mode_marker_is_accepted(tmp_file, monkeypatch):
    expected = _sha256_of(tmp_file)
    monkeypatch.setattr(
        updater.requests,
        "get",
        lambda *a, **kw: _FakeResponse(f"{expected} *WinZapp.zip\n"),
    )

    ok, detail = updater._verify_sha256sums(
        tmp_file, "WinZapp.zip", "https://x/SHA256SUMS.txt"
    )
    assert ok is True, detail


def test_comments_and_blank_lines_are_ignored(tmp_file, monkeypatch):
    expected = _sha256_of(tmp_file)
    manifest = f"\n# generated by CI\n{expected}  WinZapp.zip\n"
    monkeypatch.setattr(
        updater.requests, "get", lambda *a, **kw: _FakeResponse(manifest)
    )

    ok, detail = updater._verify_sha256sums(
        tmp_file, "WinZapp.zip", "https://x/SHA256SUMS.txt"
    )
    assert ok is True, detail
